### ISSUE TITLE
Not all the tests run on Linux

### ISSUE THREAD

**Issue by wacumov** [Cosmo/BinaryKit#18]
Test cases that do not run on Linux:
- testMixedReadByte
- testMixedReadBytes
- testReadBytesThrowsBeforeReading
- testReadBitsThrowsBeforeReading
- testBool

**Comment by Cosmo** [comment]
Hi @wacumov!
it looks like, i forgot to add those tests to the `allTests` array. 
Wouldn't this help to fix the issue?

I took a look into your PR but was not sure what's going on Linux 😅 

Thanks!

**Comment by wacumov** [comment]
Hi @Cosmo! Yes, some test cases are missing on Linux. I've fixed it in the PR and have added `LinuxVerificationTests` to prevent such a situation in the future. 
[Here](https://github.com/wacumov/BinaryKit/runs/1248842855) you can see that 20 test cases runs on Linux and 21 on Mac OS (20 from `allTests` + 1 from `LinuxVerificationTests`)

**Comment by Cosmo** [comment]
Oh, I see -- smart! :D
Thanks a lot!
